#!/bin/bash

psql -p 5432 -U postgres -d postgres -c 'create database cars'
psql -p 5432 -U postgres -d cars -c "

CREATE TABLE STORE
(
STORE_ID INTEGER
,STORE_NAME VARCHAR(200)
,START_DATE DATE DEFAULT CURRENT_DATE
,END_DATE DATE DEFAULT '9999-09-09'
);

CREATE TABLE SALES_PERSON
(
SALES_PERSON_ID  INTEGER
,NAME VARCHAR(200)
,DATE_OF_JOINING DATE
,EMPLOYEE_STATUS VARCHAR(20) DEFAULT 'ACTIVE'
,DATE_OF_BIRTH DATE
,ADDRESS VARCHAR(500)
,STORE_ID INTEGER
,START_DATE DATE DEFAULT CURRENT_DATE
,END_DATE DATE DEFAULT '9999-09-09'
);

CREATE TABLE CARS
(
CAR_ID INTEGER
,MANUFACTURER_NAME VARCHAR(50)
,MODEL_NAME VARCHAR(200)
,CATEGORY VARCHAR(100)
,YEAR_OF_MANUFACTURE INTEGER
,SERIAL_NUMBER VARCHAR(100)
,WEIGHT DECIMAL(10,2)
,PRICE DECIMAL(28,6)
,START_DATE DATE DEFAULT CURRENT_DATE
,END_DATE DATE DEFAULT '9999-09-09'
);

CREATE TABLE CUSTOMER
(
CUSTOMER_ID INTEGER
,NAME  VARCHAR(50)
,CONTACT_NO  NUMERIC
,ADDRESS VARCHAR(500)
,START_DATE DATE DEFAULT CURRENT_DATE
,END_DATE DATE DEFAULT '9999-09-09'
);

CREATE TABLE CAR_TRANSACTION
(
SALES_PERSON_ID INTEGER
,CUSTOMER_ID INTEGER
,CAR_ID INTEGER
,DISCOUNT DECIMAL(5,2)
,TRANSACTION_DTTM TIMESTAMP
,START_DATE DATE DEFAULT CURRENT_DATE
,END_DATE DATE DEFAULT '9999-09-09'
);

"
